### ISSUE TITLE
statement aborts at 31: [REPLACE INTO Object

### ISSUE THREAD

**Issue by jorry** [litesuits/android-lite-orm#37]
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
W/System.err(17618):    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
W/System.err(17618):    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:972)
W/System.err(17618):    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
W/System.err(17618):    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
W/System.err(17618):    at com.litesuits.orm.db.assit.SQLStatement.execInsertWithMapping(SQLStatement.java:111)

**Comment by litesuits** [comment]
看起来是没有访问存储的权限导致的
