### ISSUE TITLE
官方Demo在某些平台(eg. 华硕平板)，插入级联数据报错

### ISSUE THREAD

**Issue by JoyHong** [litesuits/android-lite-orm#50]
01-13 13:36:16.906 20740-21066/com.litesuits.orm.samples D/Querier: ----> Query Start: SQLStatement [sql=SELECT * FROM book, bindArgs=null, mStatement=null]
01-13 13:36:16.906 20740-21066/com.litesuits.orm.samples I/SqliteDatabaseCpp: sqlite returned: error code = 1, msg = no such table: book, db=/mnt/sdcard/lite/orm/cascade.db
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err: android.database.sqlite.SQLiteException: no such table: book: , while compiling: SELECT * FROM book
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
01-13 13:36:16.914 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.assit.Querier.doQuery(Querier.java:23)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.checkTableAndQuery(CascadeSQLiteImpl.java:348)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.query(CascadeSQLiteImpl.java:304)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.queryAndPrintAll(CascadeTestActivity.java:297)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.testQueryAll(CascadeTestActivity.java:207)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.makeOrmTest(CascadeTestActivity.java:94)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.access$0(CascadeTestActivity.java:78)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity$1.run(CascadeTestActivity.java:379)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples W/System.err:     at java.lang.Thread.run(Thread.java:856)
01-13 13:36:16.921 20740-21066/com.litesuits.orm.samples I/CascadeTestActivity: Book : []
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples D/Querier: ----> Query Start: SQLStatement [sql=SELECT * FROM student, bindArgs=null, mStatement=null]
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples I/SqliteDatabaseCpp: sqlite returned: error code = 1, msg = no such table: student, db=/mnt/sdcard/lite/orm/cascade.db
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples W/System.err: android.database.sqlite.SQLiteException: no such table: student: , while compiling: SELECT * FROM student
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
01-13 13:36:16.929 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.assit.Querier.doQuery(Querier.java:23)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.checkTableAndQuery(CascadeSQLiteImpl.java:348)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.query(CascadeSQLiteImpl.java:304)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.queryAndPrintAll(CascadeTestActivity.java:297)
01-13 13:36:16.937 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.testQueryAll(CascadeTestActivity.java:208)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.makeOrmTest(CascadeTestActivity.java:94)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.access$0(CascadeTestActivity.java:78)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity$1.run(CascadeTestActivity.java:379)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at java.lang.Thread.run(Thread.java:856)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples I/CascadeTestActivity: Student : []
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples D/Querier: ----> Query Start: SQLStatement [sql=SELECT * FROM teacher, bindArgs=null, mStatement=null]
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples I/SqliteDatabaseCpp: sqlite returned: error code = 1, msg = no such table: teacher, db=/mnt/sdcard/lite/orm/cascade.db
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err: android.database.sqlite.SQLiteException: no such table: teacher: , while compiling: SELECT * FROM teacher
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
01-13 13:36:16.945 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.assit.Querier.doQuery(Querier.java:23)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.checkTableAndQuery(CascadeSQLiteImpl.java:348)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.query(CascadeSQLiteImpl.java:304)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.queryAndPrintAll(CascadeTestActivity.java:297)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.testQueryAll(CascadeTestActivity.java:209)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.makeOrmTest(CascadeTestActivity.java:94)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.access$0(CascadeTestActivity.java:78)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity$1.run(CascadeTestActivity.java:379)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err:     at java.lang.Thread.run(Thread.java:856)
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples I/CascadeTestActivity: Teacher : []
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples D/Querier: ----> Query Start: SQLStatement [sql=SELECT * FROM class, bindArgs=null, mStatement=null]
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples I/SqliteDatabaseCpp: sqlite returned: error code = 1, msg = no such table: class, db=/mnt/sdcard/lite/orm/cascade.db
01-13 13:36:16.953 20740-21066/com.litesuits.orm.samples W/System.err: android.database.sqlite.SQLiteException: no such table: class: , while compiling: SELECT * FROM class
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.assit.Querier.doQuery(Querier.java:23)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.checkTableAndQuery(CascadeSQLiteImpl.java:348)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.query(CascadeSQLiteImpl.java:304)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.queryAndPrintAll(CascadeTestActivity.java:297)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.testQueryAll(CascadeTestActivity.java:210)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.makeOrmTest(CascadeTestActivity.java:94)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.access$0(CascadeTestActivity.java:78)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity$1.run(CascadeTestActivity.java:379)
01-13 13:36:16.960 20740-21066/com.litesuits.orm.samples W/System.err:     at java.lang.Thread.run(Thread.java:856)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples I/CascadeTestActivity: Classes : []
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples D/Querier: ----> Query Start: SQLStatement [sql=SELECT * FROM school, bindArgs=null, mStatement=null]
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples I/SqliteDatabaseCpp: sqlite returned: error code = 1, msg = no such table: school, db=/mnt/sdcard/lite/orm/cascade.db
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err: android.database.sqlite.SQLiteException: no such table: school: , while compiling: SELECT * FROM school
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.assit.Querier.doQuery(Querier.java:23)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.checkTableAndQuery(CascadeSQLiteImpl.java:348)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.db.impl.CascadeSQLiteImpl.query(CascadeSQLiteImpl.java:304)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.queryAndPrintAll(CascadeTestActivity.java:297)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.testQueryAll(CascadeTestActivity.java:211)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.makeOrmTest(CascadeTestActivity.java:94)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity.access$0(CascadeTestActivity.java:78)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at com.litesuits.orm.samples.CascadeTestActivity$1.run(CascadeTestActivity.java:379)
01-13 13:36:16.968 20740-21066/com.litesuits.orm.samples W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by JoyHong** [comment]
有什么分析进展吗？目前级联兼容问题很严重。

**Comment by JoyHong** [comment]
有什么分析进展吗？目前级联兼容问题很严重。

**Comment by JoyHong** [comment]
有什么分析进展吗？目前级联兼容问题很严重。

**Comment by JoyHong** [comment]
有什么分析进展吗？目前级联兼容问题很严重。

**Comment by litesuits** [comment]
调用代码这块麻烦贴一下，看起来SQL没有拼接完整。: SELECT * FROM book

**Comment by litesuits** [comment]
具体的代码这块麻烦贴一下，看起来SQL没有拼接完整。: SELECT * FROM book

**Comment by JoyHong** [comment]
这个log是这个项目里的demo，在华硕平板上运行的，我没做任何修改。
