### ISSUE TITLE
android 三星手机打开数据库出问题 

### ISSUE THREAD

**Issue by XiaYongjie** [litesuits/android-lite-orm#58]
ava.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT * FROM sqlite_master WHERE type='table' ORDER BY name
	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at com.litesuits.orm.db.assit.Querier.doQuery(Querier.java:27)
	at com.litesuits.orm.db.TableManager.initAllTablesFromSQLite(TableManager.java:245)
	at com.litesuits.orm.db.TableManager.initSqlTable(TableManager.java:78)
	at com.litesuits.orm.db.TableManager.<init>(TableManager.java:73)
	at com.litesuits.orm.LiteOrm.openOrCreateDatabase(LiteOrm.java:86)
	at com.litesuits.orm.LiteOrm.<init>(LiteOrm.java:75)
	at com.litesuits.orm.db.impl.SingleSQLiteImpl.<init>(SingleSQLiteImpl.java:31)
	at com.litesuits.orm.db.impl.SingleSQLiteImpl.newInstance(SingleSQLiteImpl.java:36)
	at com.litesuits.orm.LiteOrm.newSingleInstance(LiteOrm.java:119)
	at com.uns.utils.LiteOrmDBUtil.createDb(LiteOrmDBUtil.java:28)

**Comment by XiaYongjie** [comment]
设备信息
android 6.0.1 (23)，samsung:SM-G9200:arm64-v8a

**Comment by HsiangLeekwok** [comment]
#49
